@baseUrl = http://localhost:5000/apis

#############################################
# REGISTRAR PELÍCULA VISTA
#############################################

POST {{baseUrl}}/v1/watched
Content-Type: application/json

{
    "user_id": 1,
    "movie_id": 1,
    "watched_date": "2026-07-02"
}

#############################################
# HISTORIAL DEL USUARIO
#############################################

GET {{baseUrl}}/v1/users/1/watched

#############################################
# ELIMINAR REGISTRO
#############################################

DELETE {{baseUrl}}/v1/watched/1