@baseUrl = http://localhost:5000/apis
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4MjM1NjIxMywianRpIjoiNjhmYTgxMGEtNWQ5NS00OWZmLWI1NjctYzdhMmUwNGNiZTY1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Impsb3BleiIsIm5iZiI6MTc4MjM1NjIxMywiY3NyZiI6Ijk0MWQzNTYxLTk0MWYtNDAyOC05NDQ2LTBhZjc2YmJmZTI1ZCIsImV4cCI6MTc4MjM1NzExMywidXNlcl9pZCI6MX0.7eg4-kIXtLD9vLbPoEXckjHlewmqTezTCvHugWhy2G0



#############################################
# REVIEWS - LISTAR SIMPLE (V1)
#############################################
GET {{baseUrl}}/v1/reviews
Authorization: Bearer {{token}}


#############################################
# REVIEWS - LISTAR CON JOIN (V2)
#############################################
GET {{baseUrl}}/v2/reviews
Authorization: Bearer {{token}}


#############################################
# REVIEWS - FILTRAR POR MOVIE (V3)
#############################################
GET {{baseUrl}}/v3/reviews?movie_id=1
Authorization: Bearer {{token}}


#############################################
# REVIEWS - CREAR REVIEW
#############################################
POST {{baseUrl}}/v1/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Excelente película, muy recomendada",
  "rating": 4.5,
  "user_id": 1,
  "movie_id": 1
}


#############################################
# REVIEWS - CREAR REVIEW (OTRO EJEMPLO)
#############################################
POST {{baseUrl}}/v1/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Actuaciones increíbles",
  "rating": 5,
  "user_id": 2,
  "movie_id": 2
}